### ISSUE TITLE
Error when predicting miRNA for chrMT circRNA

### ISSUE THREAD

**Issue by mlvanhorn** [annadalmolin/CRAFT#3]
Hello, 

I am trying to use CRAFT to predict miRNA binding sites for three circular RNA, one of which comes from the mitochondrial chromosome. I am able to successfully finish predictions for two of the three circular RNA but not for the mitochondrial one. CRAFT hangs for a long time (10+ hours) at this point: 

```
|...............................                                       |  45%
  ordinary text without R code

  |................................                                      |  46%
label: validated_TG (with options) 
List of 2
 $ echo   : logi FALSE
 $ include: logi FALSE
```

And then eventually ends up giving this error: 

```
Quitting from lines 842-907 (functional_predictions_all_circRNAs.Rmd)
Error in function (type, msg, asError = TRUE)  :
  Could not resolve host: multimir.org
Calls: <Anonymous> ... submit_request -> <Anonymous> -> .postForm -> <Anonymous> -> fun
In addition: Warning messages:
1: package(s) not installed when version(s) same as current; use `force = TRUE` to
  re-install: 'grid'
2: In read.table(file_gene_names, header = T, sep = "\t") :
  incomplete final line found by readTableHeader on '/data/functional_predictions/backsplice_gene_name.txt'

Execution halted

```
Here is my `backsplice_gene_name.txt` input file: 

```
circ_id	gene_names
1:16891302-16893846	NBPF1
5:89791493-89802491	POLR3G
MT:9533-9756	MT-CO3
```

Is it an issue to use sequences from the mitochondrial chromosome with CRAFT? 

Thank you for your time.

Best, 
Megan

**Comment by annadalmolin** [comment]
Hi Megan,
thank you for using CRAFT.

To answer to your question, it is not an issue to use sequences from the
mitochondrial chromosome, because also the mitochondrial chromosome is
allowed.
As proof, I ran CRAFT with your circRNAs and I had any problems (no crashes
and the execution time was of 1,45 h).

How was your params.txt file?
Did you include the AGO2 binding site file in the analysis?

Regards,
Anna


Il giorno gio 10 nov 2022 alle ore 22:39 mlvanhorn ***@***.***>
ha scritto:

**Comment by mlvanhorn** [comment]
Hi Anna, 

Thank you for the reply, that's good to know! 

My params.txt file is here:

```
root@megan-ThinkPad-P53:~/data# cat params.txt
M
hsa


hg38

score_miRNA=125, energy_miRNA=-25, dGduplex_miRNA=-22, dGopen_miRNA=-10
score_miRNA=125, energy_miRNA=-25, dGduplex_miRNA=-22, dGopen_miRNA=-10, voteFrac_RBP=0.3

```

I didn't include the AGO2 binding site file in the analysis. 

Best, 
Megan

**Comment by annadalmolin** [comment]
Hi Megan,
thank you.

Simply try to be less stringent with the parameters,f.i. use:

score_miRNA=120, energy_miRNA=-22, dGduplex_miRNA=-20, dGopen_miRNA=-11,
voteFrac_RBP=0.25

Best,
Anna


Il giorno ven 18 nov 2022 alle ore 18:26 mlvanhorn ***@***.***>
ha scritto:

**Comment by mlvanhorn** [comment]
Hi Anna, 

Thank you for the suggestion. I was finally able to get the CRAFT program to finish for all circRNA including the mitochondrial one with the modified, less stringent parameters. However, I have run into another set of problems. I needed to specify the sequence of the circRNAs I am analyzing, so I generated my own files following the README and put those into the `sequence_extraction` directory. Running CRAFT, I first ran into an error with the ORF detection, shown below:

```
Quitting from lines 94-165 (functional_predictions_single_circRNA.Rmd)
Error in read.table(file_list_ORF, header = F, sep = "\t") :
  no lines available in input
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> read.table
In addition: Warning messages:
1: In system("timedatectl", intern = TRUE) :
  running command 'timedatectl' had status 1
2: package(s) not installed when version(s) same as current; use `force = TRUE` to
  re-install: 'org.Hs.eg.db'
```

I tried removing the `ORF_detection` directory and rerunning the ORF detection analysis, which gave me the same error. I checked the `result_list_ORF.txt` file, which was empty. I thought that this might be because there are no ORFs present, so I removed "O" from the `params.txt` file and tried running CRAFT again and got the following error:

```
Quitting from lines 198-202 (functional_predictions_single_circRNA.Rmd)
Error: comparison (3) is possible only for atomic and list types
In addition: Warning messages:
1: In system("timedatectl", intern = TRUE) :
  running command 'timedatectl' had status 1
2: package(s) not installed when version(s) same as current; use `force = TRUE` to
  re-install: 'org.Hs.eg.db'

Execution halted
mv: cannot stat 'functional_predictions_single_circRNA.html': No such file or directory
```
I did some looking and found that this error can be related to the `dplyr` package. I noticed earlier in the output from the run that it said: 

```
You have loaded plyr after dplyr - this is likely to cause problems.
If you need functions from both plyr and dplyr, please load plyr first, then dplyr:
library(plyr); library(dplyr)
```

I'm not sure why this seems to be causing an issue now since it didn't before when I was letting CRAFT do the sequence extraction.

Do you have any suggestions on how to solve this problem? I can also open this as a separate issue if you prefer. 

Thank you again for all of your help.

Best, 
Megan

**Comment by annadalmolin** [comment]
Hi Megan,
I'm happy you was able to successfully run CRAFT.

Yes, please open a new issue.

Anna

Il ven 6 gen 2023, 23:30 mlvanhorn ***@***.***> ha scritto:
