### ISSUE TITLE
Alternative Graphical_Output Figure File Type?

### ISSUE THREAD

**Issue by mlvanhorn** [annadalmolin/CRAFT#6]
Hello, 

Is it possible to produce the figures in the graphical_output folder in any other format than .png? Specifically, I'm trying to produce them as .eps files.

Thank you for your time. 

Best, 
Megan

**Comment by annadalmolin** [comment]
Hi Megan,
thank you for using CRAFT!

Currently, there is no option in CRAFT to change the output figure format.

Best,
Anna
